<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows10.0.26100.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>
    <RootNamespace>MyNotes.Infrastructure</RootNamespace>
    <RuntimeIdentifiers>win-x86;win-x64;win-arm64</RuntimeIdentifiers>
    <UseWinUI>true</UseWinUI>
    <WinUISDKReferences>false</WinUISDKReferences>
    <Platforms>ARM64;x64;x86;AnyCPU</Platforms>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <RunAnalyzersDuringLiveAnalysis>true</RunAnalyzersDuringLiveAnalysis>
    <SignAssembly>True</SignAssembly>
    <AssemblyOriginatorKeyFile>C:\Projects\MyNotes\Security\MyNotes.snk</AssemblyOriginatorKeyFile>
  </PropertyGroup>
  
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.7" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.7">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.7" />
    <PackageReference Include="Lucene.Net" Version="4.8.0-beta00017" />
    <PackageReference Include="Lucene.Net.Analysis.Common" Version="4.8.0-beta00017" />
    <PackageReference Include="Lucene.Net.Queries" Version="4.8.0-beta00017" />
    <PackageReference Include="Lucene.Net.QueryParser" Version="4.8.0-beta00017" />
    <PackageReference Include="Lucene.Net.Sandbox" Version="4.8.0-beta00017" />
    <PackageReference Include="Microsoft.WindowsAppSDK" Version="1.8.260416003" />
  </ItemGroup>
  
  <ItemGroup>
    <ProjectReference Include="..\MyNotes.Application.Contracts\MyNotes.Application.Contracts.csproj" />
    <ProjectReference Include="..\MyNotes.Common\MyNotes.Common.csproj" />
    <ProjectReference Include="..\MyNotes.Domain\MyNotes.Domain.csproj" />
    <ProjectReference Include="..\MyNotes.Shared\MyNotes.Shared.csproj" />
  </ItemGroup>
  
</Project>