<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows10.0.26100.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>
    <RootNamespace>MyNotes.Application</RootNamespace>
    <RuntimeIdentifiers>win-x86;win-x64;win-arm64</RuntimeIdentifiers>
    <Platforms>ARM64;x64;x86;AnyCPU</Platforms>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="Validators\**" />
    <Content Remove="Validators\**" />
    <EmbeddedResource Remove="Validators\**" />
    <None Remove="Validators\**" />
    <Page Remove="Validators\**" />
    <PRIResource Remove="Validators\**" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="DotNext" Version="6.6.1" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.11" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\MyNotes.Application.Contracts\MyNotes.Application.Contracts.csproj" />
    <ProjectReference Include="..\MyNotes.Common\MyNotes.Common.csproj" />
    <ProjectReference Include="..\MyNotes.Debugging\MyNotes.Debugging.csproj" />
    <ProjectReference Include="..\MyNotes.Domain\MyNotes.Domain.csproj" />
  </ItemGroup>
  
</Project>