<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows10.0.26100.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>
    <RootNamespace>MyNotes.Application</RootNamespace>
    <RuntimeIdentifiers>win-x86;win-x64;win-arm64</RuntimeIdentifiers>
    <UseWinUI>true</UseWinUI>
    <WinUISDKReferences>false</WinUISDKReferences>
    <Platforms>ARM64;x64;x86;AnyCPU</Platforms>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <RunAnalyzersDuringLiveAnalysis>True</RunAnalyzersDuringLiveAnalysis>
    <SignAssembly>True</SignAssembly>
    <AssemblyOriginatorKeyFile>C:\Projects\MyNotes\Security\MyNotes.snk</AssemblyOriginatorKeyFile>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.7" />
    <PackageReference Include="Microsoft.Windows.SDK.BuildTools" Version="10.0.28000.1721" />
    <PackageReference Include="Microsoft.WindowsAppSDK" Version="1.8.260416003" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\MyNotes.Application.Contracts\MyNotes.Application.Contracts.csproj" />
    <ProjectReference Include="..\MyNotes.Common\MyNotes.Common.csproj" />
    <ProjectReference Include="..\MyNotes.Domain\MyNotes.Domain.csproj" />
    <ProjectReference Include="..\MyNotes.Shared\MyNotes.Shared.csproj" />
    <ProjectReference Include="..\MyNotes.Templates\MyNotes.Templates.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Services\Notes\NewFolder\" />
    <Folder Include="Validators\Notes\" />
    <Folder Include="Validators\Navigations\" />
  </ItemGroup>
  
</Project>