<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows10.0.26100.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>
    <RootNamespace>MyNotes.Application.Contracts</RootNamespace>
    <RuntimeIdentifiers>win-x86;win-x64;win-arm64</RuntimeIdentifiers>
    <Platforms>ARM64;x64;x86;AnyCPU</Platforms>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <RunAnalyzersDuringLiveAnalysis>true</RunAnalyzersDuringLiveAnalysis>
    <SignAssembly>False</SignAssembly>
    <AssemblyOriginatorKeyFile>C:\Projects\MyNotes\Security\MyNotes.snk</AssemblyOriginatorKeyFile>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="Query\**" />
    <Content Remove="Query\**" />
    <EmbeddedResource Remove="Query\**" />
    <None Remove="Query\**" />
    <Page Remove="Query\**" />
    <PRIResource Remove="Query\**" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="DotNext" Version="6.5.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.10" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.10" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\MyNotes.Common\MyNotes.Common.csproj" />
    <ProjectReference Include="..\MyNotes.Domain\MyNotes.Domain.csproj" />
  </ItemGroup>
  
</Project>