<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows10.0.26100.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>
    <RootNamespace>MyNotes.Tests</RootNamespace>
    <RuntimeIdentifiers>win-x86;win-x64;win-arm64</RuntimeIdentifiers>
    <Platforms>x64;x86;ARM64</Platforms>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <IsTestProject>true</IsTestProject>
    <IsPackable>false</IsPackable>
    <Configurations>Debug;Release</Configurations>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="MSTest" Version="4.3.3" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\MyNotes.Application.Contracts\MyNotes.Application.Contracts.csproj" />
    <ProjectReference Include="..\MyNotes.Application\MyNotes.Application.csproj" />
    <ProjectReference Include="..\MyNotes.Common\MyNotes.Common.csproj" />
    <ProjectReference Include="..\MyNotes.Domain\MyNotes.Domain.csproj" />
    <ProjectReference Include="..\MyNotes.Infrastructure\MyNotes.Infrastructure.csproj" />
    <ProjectReference Include="..\MyNotes\MyNotes.csproj" />
  </ItemGroup>
  
</Project>
