<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.26100.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>
    <RootNamespace>MyNotes</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <Platforms>x86;x64;ARM64;AnyCPU</Platforms>
    <RuntimeIdentifiers>win-x86;win-x64;win-arm64</RuntimeIdentifiers>
    <UseWinUI>true</UseWinUI>
    <WinUISDKReferences>false</WinUISDKReferences>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <RunAnalyzersDuringLiveAnalysis>true</RunAnalyzersDuringLiveAnalysis>
    <DefineConstants>$(DefineConstants);DISABLE_XAML_GENERATED_MAIN</DefineConstants>
  </PropertyGroup>
  <ItemGroup>
    <None Remove="Views\Dialogs\SelectNoteParentDialog.xaml" />
    <None Remove="Views\Media\ImageViewerPage.xaml" />
    <None Remove="Views\Navigations\BookmarksPage.xaml" />
    <None Remove="Views\Navigations\TrashPage.xaml" />
    <None Remove="Views\Windows\ImageViewerWindow.xaml" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="AppIcon.ico" />
  </ItemGroup>

  <ItemGroup>
    <Manifest Include="$(ApplicationManifest)" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="CommunityToolkit.WinUI.Behaviors" Version="8.2.251219" />
    <PackageReference Include="CommunityToolkit.WinUI.Controls.ColorPicker" Version="8.2.251219" />
    <PackageReference Include="CommunityToolkit.WinUI.Controls.Segmented" Version="8.2.251219" />
    <PackageReference Include="CommunityToolkit.WinUI.Controls.SettingsControls" Version="8.2.251219" />
    <PackageReference Include="CommunityToolkit.WinUI.Controls.Sizers" Version="8.2.251219" />
    <PackageReference Include="CommunityToolkit.WinUI.Extensions" Version="8.2.251219" />
    <PackageReference Include="CommunityToolkit.WinUI.Helpers" Version="8.2.251219" />
    <PackageReference Include="CommunityToolkit.WinUI.Media" Version="8.2.251219" />
    <PackageReference Include="DotNext" Version="6.5.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.10" />
    <PackageReference Include="Microsoft.VisualStudio.VsixColorCompiler" Version="17.11.35325.10" />
    <PackageReference Include="Microsoft.Windows.SDK.BuildTools" Version="10.0.28000.2526" />
    <PackageReference Include="Microsoft.WindowsAppSDK" Version="2.3.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MyNotes.Application\MyNotes.Application.csproj" />
    <ProjectReference Include="..\MyNotes.Common\MyNotes.Common.csproj" />
    <ProjectReference Include="..\MyNotes.Debugging\MyNotes.Debugging.csproj" />
    <ProjectReference Include="..\MyNotes.Domain\MyNotes.Domain.csproj" />
    <ProjectReference Include="..\MyNotes.Infrastructure\MyNotes.Infrastructure.csproj" />
    <ProjectReference Include="..\MyNotes.Presentation.Contracts\MyNotes.Presentation.Contracts.csproj" />
    <ProjectReference Include="..\MyNotes.Templates\MyNotes.Templates.csproj" />
    <ProjectReference Include="..\MyNotes.Analyzer\MyNotes.Analyzer.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
  </ItemGroup>

  <ItemGroup>
    <Page Update="Views\Windows\ImageViewerWindow.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>

  <ItemGroup>
    <Page Update="Views\Dialogs\SelectNoteParentDialog.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>

  <ItemGroup>
    <Page Update="Views\Navigations\TrashPage.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>

  <ItemGroup>
    <Page Update="Views\Navigations\BookmarksPage.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>

  <ItemGroup>
    <Page Update="Views\Media\ImageViewerPage.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Services\Notes\" />
    <Folder Include="Services\Updates\Note\" />
  </ItemGroup>

    <!-- Publish Properties -->
  <PropertyGroup>
    <PublishReadyToRun Condition="'$(Configuration)' == 'Debug'">False</PublishReadyToRun>
    <PublishReadyToRun Condition="'$(Configuration)' != 'Debug'">True</PublishReadyToRun>
    <PublishTrimmed Condition="'$(Configuration)' == 'Debug'">False</PublishTrimmed>
    <PublishTrimmed Condition="'$(Configuration)' != 'Debug'">True</PublishTrimmed>
    <ApplicationIcon>AppIcon.ico</ApplicationIcon>
    <SignAssembly>False</SignAssembly>
    <AssemblyOriginatorKeyFile>C:\Projects\MyNotes\Security\MyNotes.snk</AssemblyOriginatorKeyFile>
  </PropertyGroup>
</Project>